### ISSUE TITLE
How to show search results for only Javascript in MDN?

### ISSUE THREAD

**Issue by ianizaguirre** [gilbarbara/alfred-workflows#4]
I downloaded it and added this workflow. But I noticed that the url is not specific, like I would want to choose just to search only this part of MDN `/en-US/docs/Web/JavaScript/... `

is there a way to change this as a variable or another option to ignore all other parts of mdn that arent Javascript in the search results?

**Comment by ianizaguirre** [comment]
closed by mistake , still looking for help lol

**Comment by ongaq** [comment]
It may have already been solved, but how about changing `$apiURL` to:
```
$apiURL = 'https://developer.mozilla.org/api/v1/search/en-US?topic=js&q=';
```

**Comment by ianizaguirre** [comment]
> It may have already been solved, but how about changing `$apiURL` to:
> 
> ```
> $apiURL = 'https://developer.mozilla.org/api/v1/search/en-US?topic=js&q=';
> ```

@ongaq Yea I saw that in the code itself but I am not sure how to change that variable within the actual Alfred Settings. So when I go to powerpack and click on this workflow, I don't see an easy way to adjust this url. From what I am seeing, I would have to fork this on my own to change the url and make my own workflow, or is there any easier way?

**Comment by ongaq** [comment]
If you rename `MDNSearch.alfredworkflow` to `MDNSearch.zip` and unzip it, search.php is included, so after rewriting it, compress it to zip in the same way and then you can use it if you return to `MDNSearch.alfredworkflow`!

**Comment by ianizaguirre** [comment]
@ongaq if you unzip it and then just zip it again and rename it back to `MDNSearch.alfredworkflow` the file size increases for some reason from 18kb to 19kb and then the error that its an invalid workflow shows up when trying to import it....

Found another way to solve it though, all  I had to do was find the workflow location that was already unzipped and being used by alfred and edit the file there. This way it avoids me having to zip and unzip anything because i found the file location alfred references when a workflow is added, you can do this easily by clicking here: 
![image](https://user-images.githubusercontent.com/29879270/70201998-34a8fa80-16e6-11ea-814a-dab7a0733105.png)
